### ISSUE TITLE
Handle expiry

### ISSUE THREAD

**Issue by kj7rrv** [CatimaLoyalty/catima.py#2]
This needs to handle expiry dates properly. They should be stored as UTC `datetime` objects and converted to and from Unix timestamps when converting `Card`s to and from URLs.

**Comment by kj7rrv** [comment]
Is it safe to assume users will not be storing cards that expired before 1970?

**Comment by TheLastProject** [comment]
I stored it as UNIX time so that is kinda the assumption I made too yeah. I forgot to ensure that you can't choose an earlier date on Catima Android, so I created https://github.com/CatimaLoyalty/Android/issues/753 for that, but I think it's totally sane to not accept any expiry before January 1st 1970.

**Comment by kj7rrv** [comment]
Okay. :) I figured it wouldn't be an issue, but I wanted to make sure before using -1 as a special value meaning no expiration.

**Comment by TheLastProject** [comment]
In Android I simply store NULL in the database if there is no expiry. In exports I just export an empty CSV field: https://github.com/CatimaLoyalty/Android/blob/6efe0f6c540c8562d410037efb9087c28145d36f/app/src/main/java/protect/card_locker/importexport/CatimaExporter.java#L148

So for consistency with the export format you may be best off also storing it as a nullable value instead of using -1.

**Comment by kj7rrv** [comment]
I'd already written the code using -1, but in 29d8e5a I made it raise an exception when the expiry is accessed if it is -1, and accept any falsy (e.g. `None` [Python equivalent of `null`] or empty string) value as equal to -1.
